del /s /F *.bak
del /s /F *.asv
del /s /F MakefileX
del /s /F MakefileXX
del /s /F *.batX
del /s /F *.batXX
del /s /F *.cX
del /s /F *.cXX
del /s /F *.cppX
del /s /F *.cppXX
del /s /F *.hX
del /s /F *.hXX
del /s /F *.libX
del /s /F *.libXX
del /s /F *.logX
del /s /F *.logXX
del /s /F *.defX
del /s /F *.defXX
del /s /F *.vcprojX
del /s /F *.vcprojXX
del /s /F *.rcX
del /s /F *.rcXX
del /s /F *.icoX
del /s /F *.icoXX
del /s /F *.rc2X
del /s /F *.rc2XX
del /s /F *.bmpX
del /s /F *.bmpXX
del /s /F *.txtX
del /s /F *.txtXX
del /s /F *.mX
del /s /F *.mXX
del /s /F *.uiX
del /s /F *.uiXX
del /s /F *.proX
del /s /F *.proXX
del /s /F .cprojectX
del /s /F .cprojectXX
del /s /F .projectX
del /s /F .projectXX
del /s /F *.proX
del /s /F *.proXX
del /s /F *.qrcX
del /s /F *.qrcXX
del /s /F *.slnX
del /s /F *.slnXX
del /s /F *.vdprojX
del /s /F *.vdprojXX
del /s /F *.logX
del /s /F *.logXX
del /s /F *.hmX
del /s /F *.hmXX
del /s /F *.vspropsX
del /s /F *.vspropsXX
del /s /F *.vcproj.userX
del /s /F *.vcproj.userXX
del /s /F CkiLib.log
del /s /F *.txn
del /s /F *.txnX
del /s /F *.txnXX
del /s /F *.pdfX
del /s /F *.pdfXX
del /s /F *.docX
del /s /F *.docXX
del /s /F *.LGPLX
del /s /F *.LGPLXX
del /s /F *.aa??+????
del /s /F *.dllX
del /s /F *.dllXX
del /s /F *.objX
del /s /F *.objXX
del /s /F *.exeX
del /s /F *.exeXX
del /s /F *.cbpX
del /s /F *.cbpXX
del /s /F *.msmX
del /s /F *.msmXX
del /s /F moc_*.cpp
del /s /F moc_*.h

